apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-app-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hussrafa/HELM-CHART.git
    targetRevision: main
    path: react-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default