apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicename }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.selectorLabels }}
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000